### ISSUE TITLE
SyntaxError: invalid syntax in /xgoogle/search.py, line 124

### ISSUE THREAD

**Issue by kenorb** [mycognitive/xgoogle#7]
$ ./google_dl.py 
	Traceback (most recent call last):
	  File "./google_dl.py", line 11, in <module>
	    from xgoogle.search import GoogleSearch, SearchError
	  File "/usr/local/lib/python3.2/dist-packages/xgoogle-1.4-py3.2.egg/xgoogle/search.py", line 124
	    self._re_search_strings = ("Ergebnisse", "von", u"ungefähr")
	                                                               ^
	SyntaxError: invalid syntax

**Comment by d-a-t-a-d-i-t** [comment]
On which Debian version did you encounter this error?

**Comment by d-a-t-a-d-i-t** [comment]
Probably caused by a missing locale setting (e.g. en_GB.UTF-8)...

**Comment by kenorb** [comment]
Debian GNU/Linux 7 (wheezy)

**Comment by kenorb** [comment]
Tried to reconfigure locale via dpkg, didn't help

**Comment by d-a-t-a-d-i-t** [comment]
Okay, then I'm going to check it. How urgent is it? Any deadline?

**Comment by kenorb** [comment]
@d-a-t-a-d-i-t Created an account for you, check gitter, whenever you've time.
